"""Hue's simulated worlds: the World API client and the agent handoff helpers.

A world is created after the case's execution starts, hands the agent provider mirror URLs and
a world token (never the project key), is finished and ``wait_for_seal`` completes before the
execution completes, and is read back as evaluator-only evidence once sealed. No agent framework
or tool binding is required.
"""

from .client import EnvironmentClient, EnvironmentSealTimeoutError, HueEnvironmentError
from .types import (
    ActionDefinition,
    ActionParameter,
    ActionResult,
    ActionSchema,
    CoverageGap,
    CoverageGapReporter,
    CoverageGapResult,
    Effect,
    EnvironmentCoverage,
    EnvironmentRun,
    ErrorObservation,
    FinishStatus,
    Json,
    LegacyMcpCapability,
    Observation,
    OkObservation,
    RunState,
    RunStatus,
    SealedRun,
    Step,
    StepPage,
    WorldEvidenceSection,
    WorldFlag,
    WorldHandoff,
    WorldLifecycle,
    WorldMcpConfig,
    WorldMcpServer,
    WorldSurface,
)
from .world import (
    HUE_CONTROL_PLANE_VARIABLES,
    agent_environment,
    is_hue_control_plane_credential,
    legacy_mcp_capability,
    mcp_config_file,
    strip_hue_control_plane_credentials,
    world_handoff,
)

__all__ = [
    "ActionDefinition",
    "ActionParameter",
    "ActionResult",
    "ActionSchema",
    "CoverageGap",
    "CoverageGapReporter",
    "CoverageGapResult",
    "Effect",
    "EnvironmentClient",
    "EnvironmentSealTimeoutError",
    "EnvironmentCoverage",
    "EnvironmentRun",
    "ErrorObservation",
    "FinishStatus",
    "HUE_CONTROL_PLANE_VARIABLES",
    "HueEnvironmentError",
    "Json",
    "LegacyMcpCapability",
    "Observation",
    "OkObservation",
    "RunState",
    "RunStatus",
    "SealedRun",
    "Step",
    "StepPage",
    "WorldEvidenceSection",
    "WorldFlag",
    "WorldHandoff",
    "WorldLifecycle",
    "WorldMcpConfig",
    "WorldMcpServer",
    "WorldSurface",
    "agent_environment",
    "is_hue_control_plane_credential",
    "legacy_mcp_capability",
    "mcp_config_file",
    "strip_hue_control_plane_credentials",
    "world_handoff",
]
