// Writes src/version.ts from package.json so the published code carries a literal version
// instead of reading package.json at import time (which breaks under bundlers). Run by `bun run build`;
// `--check` fails when the committed file is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const target = join(root, "src", "version.ts");
const content = `// Generated by scripts/write-version.mjs from package.json; do not edit by hand.
/** Package version shared by the instrumentation scope and the export User-Agent. */
export const sdkVersion = ${JSON.stringify(version)};
`;
let current = "";
try {
  current = readFileSync(target, "utf8");
} catch {
  current = "";
}
if (process.argv.includes("--check")) {
  if (current !== content) {
    console.error(
      `src/version.ts does not match package.json (${version}); run \`bun run build\`.`,
    );
    process.exit(1);
  }
} else if (current !== content) {
  writeFileSync(target, content);
}
