// Generated by scripts/write-version.mjs from package.json; do not edit by hand.
/** Package version shared by the instrumentation scope and the export User-Agent. */
export const sdkVersion = "0.6.0";
